# Generated by Django 6.0.4 on 2026-05-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REJECTED', 'Rejected'), ('FROZEN', 'Frozen'), ('LOCKED', 'Locked')], default='PENDING', max_length=10),
        ),
    ]
