# Generated by Django 6.0.4 on 2026-05-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_bankaccount_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='status',
            field=models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Verification'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('FROZEN', 'Frozen'), ('LOCKED', 'Locked'), ('REJECTED', 'Rejected')], default='PENDING_VERIFICATION', max_length=20),
        ),
    ]
