# Generated by Django 6.0.4 on 2026-05-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_bankaccount_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='currency',
            field=models.CharField(choices=[('GBP', 'British Pound'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='GBP', max_length=3),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
