# Generated by Django 6.0.4 on 2026-05-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_bankaccount_currency_bankaccount_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='card_blocked_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='card_cvv',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='card_daily_limit',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='card_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='card_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='card_pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='card_status',
            field=models.CharField(choices=[('NOT_ISSUED', 'Not Issued'), ('PENDING', 'Pending Approval'), ('ISSUED', 'Issued'), ('ACTIVE', 'Active'), ('BLOCKED', 'Blocked'), ('EXPIRED', 'Expired')], default='NOT_ISSUED', max_length=15),
        ),
    ]
