# Generated by Django 6.0.4 on 2026-05-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_transaction_pin_alter_user_role_kycverification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
