# Generated by Django 6.0.4 on 2026-05-15 05:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('TRANSACTION_SUMMARY', 'Transaction Summary'), ('ACCOUNT_ACTIVITY', 'Account Activity'), ('CUSTOMER_ANALYTICS', 'Customer Analytics'), ('COMPLIANCE_REPORT', 'Compliance Report')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('parameters', models.JSONField(default=dict)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('status', models.CharField(choices=[('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='GENERATING', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
