# Generated by Django 6.0.4 on 2026-05-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CUSTOMER_APPROVED', 'Customer Approved'), ('CUSTOMER_REJECTED', 'Customer Rejected'), ('CUSTOMER_VERIFIED', 'Customer Verified'), ('ACCOUNT_CREATED', 'Account Created'), ('ACCOUNT_APPROVED', 'Account Approved'), ('ACCOUNT_REJECTED', 'Account Rejected'), ('ACCOUNT_FROZEN', 'Account Frozen'), ('ACCOUNT_SUSPENDED', 'Account Suspended'), ('ACCOUNT_REACTIVATED', 'Account Reactivated'), ('ACCOUNT_LOCKED', 'Account Locked'), ('ACCOUNT_UNLOCKED', 'Account Unlocked'), ('PASSWORD_RESET', 'Password Reset'), ('DEPOSIT_MADE', 'Deposit Made'), ('WITHDRAWAL_MADE', 'Withdrawal Made'), ('TRANSFER_MADE', 'Transfer Made'), ('TRANSFER_REVERSED', 'Transfer Reversed'), ('MESSAGE_SENT', 'Message Sent'), ('PROFILE_UPDATED', 'Profile Updated'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('KYC_SUBMITTED', 'KYC Submitted'), ('KYC_APPROVED', 'KYC Approved'), ('KYC_REJECTED', 'KYC Rejected'), ('SETTINGS_CHANGED', 'Settings Changed'), ('TRANSACTION_PIN_SET', 'Transaction PIN Set')], max_length=30),
        ),
    ]
