# Generated by Django 6.0.4 on 2026-05-19 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='deposit_type',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash Deposit'), ('BANK_TRANSFER', 'Bank Transfer'), ('ADJUSTMENT', 'Adjustment'), ('INTEREST', 'Interest Credit')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('REVERSAL', 'Reversal'), ('CHARGE', 'Charge')], max_length=10),
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_type', models.CharField(choices=[('CASH', 'Cash Deposit'), ('BANK_TRANSFER', 'Bank Transfer'), ('ADJUSTMENT', 'Adjustment'), ('INTEREST', 'Interest Credit')], default='CASH', max_length=15)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_deposits', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_details', to='transactions.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('INTERNAL', 'Internal Transfer'), ('EXTERNAL', 'External Transfer')], default='EXTERNAL', max_length=10)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('confirmation_pin_used', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_details', to='transactions.transaction')),
            ],
        ),
    ]
