# Generated by Django 6.0.4 on 2026-05-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_balance_after_transaction_deposit_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='source_account_number',
            field=models.CharField(blank=True, help_text='External account number for transfers', max_length=20),
        ),
        migrations.AddField(
            model_name='deposit',
            name='source_platform',
            field=models.CharField(blank=True, help_text='Platform name for mobile money / online deposits', max_length=100),
        ),
        migrations.AddField(
            model_name='deposit',
            name='source_reference',
            field=models.CharField(blank=True, help_text='Reference ID from the source platform', max_length=100),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='deposit_type',
            field=models.CharField(choices=[('CASH', 'Cash Deposit'), ('BANK_TRANSFER', 'Bank Transfer'), ('ACCOUNT_TRANSFER', 'Account Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('ONLINE_PLATFORM', 'Online Platform'), ('ADJUSTMENT', 'Adjustment'), ('INTEREST', 'Interest Credit')], default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='deposit_type',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash Deposit'), ('BANK_TRANSFER', 'Bank Transfer'), ('ACCOUNT_TRANSFER', 'Account Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('ONLINE_PLATFORM', 'Online Platform'), ('ADJUSTMENT', 'Adjustment'), ('INTEREST', 'Interest Credit')], max_length=20, null=True),
        ),
    ]
