# Generated by Django 6.0.4 on 2026-05-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_deposit_source_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='external_account_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='transfer',
            name='external_bank_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
