# Generated by Django 6.0.4 on 2026-05-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ACCOUNT_APPROVED', 'Account Approved'), ('ACCOUNT_REJECTED', 'Account Rejected'), ('VERIFICATION_APPROVED', 'Verification Approved'), ('VERIFICATION_REJECTED', 'Verification Rejected'), ('DEPOSIT', 'Deposit'), ('TRANSFER_SENT', 'Transfer Sent'), ('TRANSFER_RECEIVED', 'Transfer Received'), ('ACCOUNT_SUSPENDED', 'Account Suspended'), ('ACCOUNT_FROZEN', 'Account Frozen'), ('PASSWORD_RESET', 'Password Reset'), ('KYC_REMINDER', 'KYC Reminder'), ('GENERAL', 'General')], default='GENERAL', max_length=25),
        ),
    ]
